#!/usr/bin/env bash
set -e

if [ -z ${DOCKER_IMAGE_VERSION}  ]; then
    echo 'DOCKER_IMAGE_VERSION env cannot be blank';
fi

DOCKER_ID_USER=raoptimus
DOCKER_IMAGE=yii2-php

docker build -f ./Dockerfile -t ${DOCKER_ID_USER}/${DOCKER_IMAGE}:"${DOCKER_IMAGE_VERSION}" -t ${DOCKER_ID_USER}/${DOCKER_IMAGE}:latest  ./

docker push ${DOCKER_ID_USER}/${DOCKER_IMAGE}:"${DOCKER_IMAGE_VERSION}"
docker push ${DOCKER_ID_USER}/${DOCKER_IMAGE}:latest
